### ISSUE TITLE
Proxy url

### ISSUE THREAD

**Issue by ingnelson** [evanchiu/base64-streaming-proxy#10]
Hello sir.

I want to install a proxy on UBUNTU VPS and understand a URL encode request and then forward to shadowsocks to create a tunnel to bypass my firewall. 

The client (Windows or Android ) send a encode URL encode .
Example :
GET #verx=2&0=c610d32167c94e46a48d959354202365&1=34c961c67ff3b923603867b1aecd506b&2=0&3=1&4=4&ope=1&cy=Claro-ni&7=dx1iv8o-nX8xY4AUPc9tWA==# HTTP/1.1

Can you help me , I can give you my user and pass for the vps 
Look the screenshot: 
![IMG_20200501_212110](https://user-images.githubusercontent.com/6626845/81711401-e0423d80-9430-11ea-97da-c3614a3034ac.jpg)
![IMG_20200429_101602](https://user-images.githubusercontent.com/6626845/81711406-e2a49780-9430-11ea-920c-cb8284699730.jpg)

**Comment by evanchiu** [comment]
Hello!

I'm sorry, I have no idea what this issue is about.  This project provides a base64 streaming proxy, which will allow fetching arbitary remote content as base64-encoded text.  It is not a SOCKS proxy and it is not designed for tunneling.
